name : CI/CD Node.js Pipeline # Nom visible du pipeline
on :
  push : # D c l e n c h e sur push
    branches : [ main ]
  pull_request : # D c l e n c h e sur PR
    branches : [ main ]

jobs :

  test : # Job CI
    name : Continuous Integration
    runs-on : ubuntu-latest

    steps :
      - name : Checkout repository
        uses : actions/checkout@v4 # R c u p r e le code source

      - name : Setup Node.js
        uses : actions/setup-node@v4
        with :
          node - version : 20 # Version Node . js

      - name : Install dependencies
        run : npm ci

      - name : Run unit tests
        run : npm test # chec bloque le job deploy

  deploy:
    name: Continuous Deployment
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate dynamic index.html
        run: |
          echo "<!DOCTYPE html>" > index.html
          echo "<html lang='fr'><head><meta charset='UTF-8'><title>TP Node.js CI/CD</title></head>" >> index.html
          echo "<body>" >> index.html
          echo "<h1>Bienvenue sur le TP CI/CD</h1>" >> index.html
          echo "<p>Deploiement automatique reussi !</p>" >> index.html
          echo "<p><strong>Date et heure :</strong> $(date +'%d/%m/%Y %H:%M:%S')</p>" >> index.html
          echo "<p>Ce site a ete genere par GitHub Actions.</p>" >> index.html
          echo "</body></html>" >> index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./